services:
  project-1:
    build: ./project-1
    networks:
      - nginx-network

  project-2:
    build: ./project-2
    networks:
      - nginx-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./images:/var/www/static
    depends_on:
      - project-1
      - project-2
    networks:
      - nginx-network


networks:
  nginx-network:
    driver: bridge